name: slowotok
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  confetti: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  charts_flutter_new: ^0.12.0
  intl: ^0.17.0
  adaptive_theme: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19

flutter_icons:
  image_path: assets/logo.png
  android: "launcher_icon"
  adaptive_icon_background: "#4bdd4e"

flutter_native_splash:
  image: assets/splash.png
  color: "#4bdd4e"

flutter:

  uses-material-design: true

  assets:
    - assets/4_letter_words.txt
    - assets/5_letter_words.txt
    - assets/6_letter_words.txt
    - assets/7_letter_words.txt
    - assets/all_words.txt
    - assets/icon.png
    - assets/icon2.png
    - assets/letter_correct_place.png
    - assets/letter_incorrect_place.png
    - assets/no_letter_in_word.png
