name: slowotok
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/4_letter_words.txt
    - assets/5_letter_words.txt
    - assets/6_letter_words.txt
    - assets/7_letter_words.txt
    - assets/icon.png
    - assets/letter_correct_place.png
    - assets/letter_incorrect_place.png
    - assets/no_letter_in_word.png
