name: charts_flutter_new
version: 0.12.0
description: Material Design charting library for flutter with active support
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  charts_common: ^0.12.0
  # charts_common:
  #   path: ../charts_common/
  collection:
  flutter:
    sdk: flutter
  intl:
  logging:
  meta:


dev_dependencies:
  mockito:
  build_runner:
  flutter_test:
    sdk: flutter
  test:
